/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui.modules.hit_mole {
    export class HitMoleMainUI extends View {
		public boxHammer:Laya.Box;
		public boxTips:Laya.Box;
		public labTime:Laya.Label;
		public timeBar:Laya.ProgressBar;
		public boxOver:Laya.Box;
		public labOverValue:Laya.Label;
		public btnRestart:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("modules/hit_mole/HitMoleMain");
        }
    }
    REG("ui.modules.hit_mole.HitMoleMainUI",HitMoleMainUI);
    export class HitMoleRuleUI extends View {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("modules/hit_mole/HitMoleRule");
        }
    }
    REG("ui.modules.hit_mole.HitMoleRuleUI",HitMoleRuleUI);
    export class HitMoleStartUI extends View {
		public btnStart:Laya.Button;
		public scrollLab:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("modules/hit_mole/HitMoleStart");
        }
    }
    REG("ui.modules.hit_mole.HitMoleStartUI",HitMoleStartUI);
}
export module ui.modules.login {
    export class LoginUI extends Scene {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("modules/login/Login");
        }
    }
    REG("ui.modules.login.LoginUI",LoginUI);
}
export module ui.modules.misc {
    export class RuleUI extends View {
		public labDesc:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("modules/misc/Rule");
        }
    }
    REG("ui.modules.misc.RuleUI",RuleUI);
}