/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui.modules.hit_mole {
    export class HitMoleMainUI extends View {
		public boxHammer:Laya.Box;
		public boxTips:Laya.Box;
		public labTime:Laya.Label;
		public timeBar:Laya.ProgressBar;
		public boxOver:Laya.Box;
		public labOverValue:Laya.Label;
		public btnRestart:Laya.Button;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("modules/hit_mole/HitMoleMain");
        }
    }
    REG("ui.modules.hit_mole.HitMoleMainUI",HitMoleMainUI);
    export class HitMoleRuleUI extends View {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("modules/hit_mole/HitMoleRule");
        }
    }
    REG("ui.modules.hit_mole.HitMoleRuleUI",HitMoleRuleUI);
    export class HitMoleStartUI extends View {
		public btnStart:Laya.Button;
		public scrollLab:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("modules/hit_mole/HitMoleStart");
        }
    }
    REG("ui.modules.hit_mole.HitMoleStartUI",HitMoleStartUI);
}
export module ui.modules.hp {
    export class HpSingleUI extends Scene {
		public boxVal:Laya.Box;
		public imgHp:Laya.Image;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("modules/hp/HpSingle");
        }
    }
    REG("ui.modules.hp.HpSingleUI",HpSingleUI);
    export class MainHpUI extends Scene {
		public imgHpNext:Laya.Image;
		public imgHpTween:Laya.Image;
		public imgHp:Laya.Image;
		public labHp:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("modules/hp/MainHp");
        }
    }
    REG("ui.modules.hp.MainHpUI",MainHpUI);
}
export module ui.modules.login {
    export class LoginUI extends Scene {
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("modules/login/Login");
        }
    }
    REG("ui.modules.login.LoginUI",LoginUI);
}
export module ui.modules.misc {
    export class RuleUI extends View {
		public labDesc:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("modules/misc/Rule");
        }
    }
    REG("ui.modules.misc.RuleUI",RuleUI);
}
export module ui.modules.test {
    export class TestPanelUI extends View {
		public panel:Laya.Panel;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("modules/test/TestPanel");
        }
    }
    REG("ui.modules.test.TestPanelUI",TestPanelUI);
    export class TestPanelCloudUI extends Scene {
		public panel:Laya.Panel;
		public list:Laya.List;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("modules/test/TestPanelCloud");
        }
    }
    REG("ui.modules.test.TestPanelCloudUI",TestPanelCloudUI);
    export class TestSceneUI extends Scene {
		public scoreLbl:Laya.Label;
		public tipLbll:Laya.Label;
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.loadScene("modules/test/TestScene");
        }
    }
    REG("ui.modules.test.TestSceneUI",TestSceneUI);
}